---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      #BucketName: !Sub 'bucketPublicReadWrite-${AWS::Region}-${AWS::AccountId}'
      BucketName: S3-Bucket-Name    
      PublicAccessBlockConfiguration:        
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket